### ISSUE TITLE
FlightAware Aircraft Count

### ISSUE THREAD

**Issue by bacco007** [greymatter/hass-config#1]
Hi :wave:

Liking what you've done with your Avoinics page - just wondering if you could point me to where its possible to get the aircraft count data from FlightAware

https://github.com/greymatter/hass-config/blob/1d12fd814291f20776e6bd25b9381d8a254354f7/pkg/avionics.yaml#L349-L391

**Comment by greymatter** [comment]
i'm planning to add all my queries for the SQL sensor soon, it will be in the avionics pkg when i upload it.

edited.
apologies, i read that as Flightairmap...  i've been drinking good beer tonight so my bad.  i'm pretty sure  already added all the flightaware stuff already, i'll go through it again but im pretty i sure its in there.      what exactly are you looking for?  stats wise?

**Comment by greymatter** [comment]
it'll just be comments as i've had issues with creating sql sensors in yaml.

**Comment by greymatter** [comment]
ok Hi Bacco, sober now and I have comprehended your comment.. lol.  I've repushed an update Avionics pkg with all the SQL bits as well as example URLs for all urls I hiding in secrets.  But the one i think you are looking for is this:

  - name: ADSB Aircraft Count by Type
    resource: !secret flightaware_aircraft_type
    #resource: http://10.x.x.x:8080/data/status.json

please let me know if there is still something else you need, I'd be happy to share!

**Comment by greymatter** [comment]
ok Hi Bacco, sober now and I have comprehended your comment.. lol.  I've repushed an update Avionics pkg with all the SQL bits as well as example URLs for all urls I hiding in secrets.  But the one i think you are looking for is this:

  - name: ADSB Aircraft Count by Type
    resource: !secret flightaware_aircraft_type
    #resource: http://10.x.x.x:8080/data/status.json

please let me know if there is still something else you need, I'd be happy to share!
