### ISSUE TITLE
Network Map CFG

### ISSUE THREAD

**Issue by milandzuris** [greymatter/hass-config#2]
Hi, how u make this map? cfg?

![image](https://github.com/greymatter/hass-config/assets/42905545/96f088f9-d9f2-4a44-be37-c64ce8cd67ac)

**Comment by greymatter** [comment]
let me prioritize getting the rest of this uploaded!

**Comment by greymatter** [comment]
ok so you're going to want to look at these files...

ui-dev/views/network.yaml
ui-dev/shared/cards/gmhq-network-map.yaml
ui-dev/templates/button-card/rail.yaml
ui-dev/templates/button-card/rail-rows.yaml

that should be it.  Let me know if you have any additional questions.
