### ISSUE TITLE
missing snippets

### ISSUE THREAD

**Issue by JackTerok** [greymatter/hass-config#3]
Hi. 

I was trying to implement part of your config.
It makes references to layouts at different points.
Like: snippets/layout-page-margin.yaml'

Where can I find those layouts? Or are they part of some add-ons?
Thx.

Btw: Great job on the config. The screenshots look great.

**Comment by greymatter** [comment]
ok those all should be pushed already, yeah they are here:

https://github.com/greymatter/hass-config/tree/main/ui-dev/shared/snippets

and Thanks!!  I do appreciate it!!
